import React, {useState} from 'react';
import { SafeAreaView, View, Text, Pressable, StyleSheet, ScrollView } from 'react-native';
import { StatusBar } from 'expo-status-bar';

const plans=[['Quick Scan','₹29','Fingerprint/hand scan + basic pattern'],['Complete Report','₹99','Shankh/Chakra + palm report'],['Full Life Report','₹299','Career, money, relationship & life pattern'],['Premium AI','₹599','AI consultation + personalized report'],['Annual','₹1,499/year','Premium access']];

export default function App(){
 const [screen,setScreen]=useState('home');
 const go=s=>setScreen(s);
 return <SafeAreaView style={styles.root}><StatusBar style="light"/><ScrollView contentContainerStyle={styles.wrap}>
  <Text style={styles.logo}>LIFE PATTERN</Text>
  {screen==='home' && <>
   <Text style={styles.h1}>Apna Life Pattern<br/>pehchaniye.</Text>
   <Text style={styles.sub}>Hand & fingerprint patterns ki traditional AI interpretation.</Text>
   <View style={styles.hero}><Text style={styles.eyebrow}>YOUR FIRST SCAN</Text><Text style={styles.heroTitle}>Kya aap 90% mein hain ya 10% mein?</Text><Text style={styles.muted}>Aapke scan se ek preliminary Life Pattern Score milega.</Text><Pressable style={styles.primary} onPress={()=>go('scan')}><Text style={styles.primaryText}>Start Free Scan →</Text></Pressable></View>
   <Text style={styles.section}>What we analyse</Text>
   <View style={styles.grid}>{['🖐 Palm lines','◉ Finger patterns','🌀 Shankh / Chakra','📊 Life Pattern'].map(x=><View style={styles.card} key={x}><Text style={styles.cardText}>{x}</Text></View>)}</View>
  </>}
  {screen==='scan' && <><Text style={styles.h1}>Hand Scan</Text><Text style={styles.sub}>Clear, well-lit photo upload karein. Production version mein camera guidance yahan hogi.</Text><View style={styles.scanBox}><Text style={styles.scanIcon}>🖐</Text><Text style={styles.heroTitle}>Place your hand here</Text><Text style={styles.muted}>Full palm visible • No filters • Good lighting</Text></View><Pressable style={styles.primary} onPress={()=>go('result')}><Text style={styles.primaryText}>Analyse My Hand</Text></Pressable><Pressable onPress={()=>go('home')}><Text style={styles.back}>← Back</Text></Pressable></>}
  {screen==='result' && <><Text style={styles.eyebrow}>PRELIMINARY RESULT</Text><Text style={styles.h1}>Aapka pattern</Text><View style={styles.score}><Text style={styles.scoreNum}>72</Text><Text style={styles.scoreLabel}>/100 Life Pattern Score</Text><Text style={styles.badge}>10% SUCCESS-PATTERN</Text></View><Text style={styles.heroTitle}>Opportunity + Effort balance</Text><Text style={styles.muted}>Ye AI/traditional interpretation hai; ise guaranteed future prediction na samjhein.</Text><Pressable style={styles.primary} onPress={()=>go('plans')}><Text style={styles.primaryText}>Unlock Full Report →</Text></Pressable><Pressable onPress={()=>go('home')}><Text style={styles.back}>← Home</Text></Pressable></>}
  {screen==='plans' && <><Text style={styles.h1}>Choose your reading</Text><Text style={styles.sub}>Simple pricing. ₹599 se upar koi normal plan nahi.</Text>{plans.map(p=><Pressable style={styles.plan} key={p[0]}><View><Text style={styles.planTitle}>{p[0]}</Text><Text style={styles.muted}>{p[2]}</Text></View><Text style={styles.price}>{p[1]}</Text></Pressable>)}<Pressable onPress={()=>go('home')}><Text style={styles.back}>← Home</Text></Pressable></>}
 </ScrollView></SafeAreaView>
}
const styles=StyleSheet.create({root:{flex:1,backgroundColor:'#090B18'},wrap:{padding:24,paddingBottom:50},logo:{color:'#D9B56D',fontWeight:'800',letterSpacing:3,fontSize:13,marginBottom:42},h1:{color:'#fff',fontSize:38,fontWeight:'800',lineHeight:44,marginBottom:12},sub:{color:'#A9ADC2',fontSize:16,lineHeight:24,marginBottom:28},hero:{backgroundColor:'#15182A',borderRadius:24,padding:22,borderWidth:1,borderColor:'#282D48'},eyebrow:{color:'#D9B56D',fontSize:12,fontWeight:'800',letterSpacing:1.5,marginBottom:10},heroTitle:{color:'#fff',fontSize:22,fontWeight:'700',lineHeight:29,marginBottom:10},muted:{color:'#969AAF',fontSize:14,lineHeight:21},primary:{backgroundColor:'#D9B56D',padding:16,borderRadius:14,alignItems:'center',marginTop:22},primaryText:{color:'#17130A',fontWeight:'800',fontSize:16},section:{color:'#fff',fontSize:20,fontWeight:'700',marginTop:30,marginBottom:14},grid:{flexDirection:'row',flexWrap:'wrap',gap:10},card:{backgroundColor:'#121527',padding:16,borderRadius:16,width:'48%'},cardText:{color:'#E8E9F0',fontWeight:'600'},scanBox:{height:300,borderRadius:26,borderWidth:1,borderColor:'#343953',borderStyle:'dashed',alignItems:'center',justifyContent:'center',backgroundColor:'#111426'},scanIcon:{fontSize:64,marginBottom:18},back:{color:'#D9B56D',textAlign:'center',marginTop:22,fontWeight:'700'},score:{backgroundColor:'#15182A',borderRadius:24,padding:28,alignItems:'center',marginVertical:22},scoreNum:{color:'#D9B56D',fontSize:72,fontWeight:'900'},scoreLabel:{color:'#A9ADC2',marginBottom:18},badge:{backgroundColor:'#252039',color:'#D9B56D',paddingHorizontal:14,paddingVertical:8,borderRadius:20,fontWeight:'800'},plan:{backgroundColor:'#15182A',padding:18,borderRadius:18,marginBottom:12,flexDirection:'row',justifyContent:'space-between',alignItems:'center',borderWidth:1,borderColor:'#242942'},planTitle:{color:'#fff',fontSize:17,fontWeight:'800',marginBottom:4},price:{color:'#D9B56D',fontSize:20,fontWeight:'900'}});
